VERSION 0.6

init-js:
  FROM node:16.15.0-stretch-slim
  WORKDIR /project/example/realworld/modules/service
  COPY ./package.json ./
  COPY ./yarn.lock ./
  RUN yarn install

build:
  FROM ./../../../..+build-modules
  WORKDIR /project/example/realworld/modules/service
  COPY ./main.tf ./
  RUN terraform init
  RUN terraform validate
  COPY +build-js/index.js ./
  SAVE ARTIFACT ./main.tf
  SAVE ARTIFACT ./index.js

build-js:
  FROM +init-js
  COPY ./index.js ./
  COPY ./index.spec.js ./
  RUN yarn test
  SAVE ARTIFACT ./index.js